Add Popup Html Structure
Saadat123456/Portfolio pull request #15
Opened 2022-01-25 15:17 UTC by Saadat123456

2022-01-27 17:02 UTC, mateo951 requested changes
### Hi Team, 

👌 **Your project highlights** 😎 
- Linters are set correctly ✔
- GitHub Flow implemented 👌
- JS functionality

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-27 17:02 UTC, mateo951 commented on main.css
> +
There are a few issues with your popup on desktop sizes. Kindly make sure that you follow as much as possible Figma's design 🧐 We could work on the font, text color, and margins of the popup to resemble the design! You are on the right path 😎 One last thing, the color of the x button is too light and loses itself sometimes through the design. Please make the necessary changes in order to meet the project requirements 😉

### Your design 
![image](https://user-images.githubusercontent.com/15807343/151406418-0849a73d-c3a6-4aac-aeb3-373f7572d921.png)

### Figma'
![Captura](https://user-images.githubusercontent.com/15807343/151406451-8782911c-55d6-47b4-ba90-cbc8811aa3be.PNG)
s

2022-01-27 23:44 UTC, sheylaPozo commented
## Status: ✔️ Project Approved ✔️ 
----

Hello @Saadat123456 🔥 

> # Excellent work on your project, it looks very professional and it's completed. Congrats on the good work!

![surprised](https://user-images.githubusercontent.com/60631456/122959988-c881fc00-d348-11eb-988a-a5aa782f4777.gif)

Now you can celebrate! 🥇 🚀 👍 💯 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️
`There's nothing left to say but time to merge! 😊`

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 23:51 UTC, sheylaPozo commented
## Optional Suggestions 
---

- [x] Would look better if you re-check that the `see project` button works in your last update of deployment, I've tried to run the project and open the live link and press the `see project` button but hasn't shown me the pop-up window, I know it might be that the last update deployed branch is behind the deployed project, so just in case try to deploy it again with your last made changes, and run the project checks to see if all works properly, since this project you will use it until the end of Microverse and all have to run correctly. Since this is an optional suggestion, doesn't hold you back from approval, good job doing all the required changes, your project's been approved. ✔😊
![check](https://user-images.githubusercontent.com/54015740/151462069-3fe0de0f-389c-45ea-8e2d-a6d5e657a9fe.png)👍 💯 

![tenor](https://user-images.githubusercontent.com/54015740/127129480-dfb12898-5429-4ff7-a67a-f4e3df0edc64.gif)

2022-01-28 00:06 UTC, merged

2022-01-28 13:35 UTC, sheylaPozo commented
@Saadat123456  When I reviewed it, I saw all the checks were running, kindly fix the linter errors, senior reviewers will check, and it seems like your pop up window is still not functioning and there's a linter error, you can fix with the auto-fix option `--fix`

2022-01-28 13:40 UTC, sheylaPozo commented
### Optional changes ♻

@Saadat123456 When I reviewed it, I saw all the checks were running, kindly fix the linter errors, senior reviewers will check for conformities and notice there's a linker error, you can fix it with the auto-fix option --fix or go one by one manually until all the linter errors are corrected 😁📌

2022-01-28 13:41 UTC, sheylaPozo commented
### Optional changes ♻

@Saadat123456 When I reviewed it, I saw all the checks were running so I proceed to approve, seems like there was some change that caused a linter error before you merged into main, kindly fix the linter errors, senior reviewers will check for conformities and notice there's a linter error, you can fix it with the auto-fix option `--fix` or go one by one manually until all the linter errors are corrected 😁📌